### ISSUE TITLE
Networking: move MQTT and SNTP configs from sdkconfig to code?

### ISSUE THREAD

**Issue by adamoferro** [ogghst/grownode#24]
The idea would be to avoid using menuconfig except for advanced stuff, making the code the single point of configuration for a general "basic" user, who wouldn't even need to know about menuconfig.

**Comment by ogghst** [comment]
done with today's commit. configuration is now in main.c. 
in order to see the changes, please launch an 'idf.py menuconfig' and browse to the grownode component configuration

**Comment by adamoferro** [comment]
Well done! It seems to work smoothly.
Sure it has been a simple thing to implement 😬
